CREATE OR REPLACE FUNCTION triggerfunc()
RETURNS trigger
AS $function$
DECLARE 
  L_COUNT_OF_STATIONS INTEGER := COUNT_STATIONS(OLD.START_STATIONNUMBER, NEW.END_STATIONNUMBER, OLD.START_LINEID);
  L_OPERATORNAME varchar;
  L_CHILD_ADULT CHAR;
  L_FAREZONE INTEGER DEFAULT NULL;
  L_ZONE_ID INTEGER DEFAULT NULL;
  L_PRICE NUMERIC;
BEGIN
  RAISE INFO 'COMPLETE_TRIP'; 
  
  --YOUR CODE HERE
  RETURN NEW;  
  
END;
$function$
LANGUAGE plpgsql;

create TRIGGER COMPLETE_TRIP 
-- TRIGGER PARAMETERS HERE
EXECUTE PROCEDURE triggerfunc();

